#!/usr/bin/env bash
# Drain a job queue on one GPU. Survives SSH loss / laptop sleep (launched with
# setsid nohup). A failing job never stops the queue.
#
#   worker.sh <gpu_id> <queue_file>
#
# Queue lines are shell command tails passed to run_job.sh, e.g.
#   train G01_mvf50 --max_video_frames 50 --n_epochs 10 ...
# Blank lines and lines starting with # are ignored.
set -uo pipefail

GPU="$1"
QUEUE="$2"
# Second/third worker on the same GPU passes "nophase2": only the primary
# worker per GPU generates and drains the phase-2 queue, or they would
# duplicate every phase-2 job.
ROLE="${3:-primary}"
TAG="${4:-$GPU}"
source "$(dirname "$0")/common.sh"
cd "$ROOT"

export CUDA_VISIBLE_DEVICES="$GPU"
LOG="$OUT_ROOT/worker_gpu${TAG}.log"
mkdir -p "$OUT_ROOT"

echo "[worker$TAG] start $(date -Is) queue=$QUEUE" >> "$LOG"

# Phase loop: after a queue drains, look for a phase-2 queue generated by
# phase2.py and drain that too.
while :; do
  [[ -f "$QUEUE" ]] || { echo "[worker$TAG] no queue $QUEUE" >> "$LOG"; break; }

  while IFS= read -r line; do
    [[ -z "${line// }" ]] && continue
    [[ "$line" == \#* ]] && continue
    echo "[worker$TAG] >>> $line  $(date -Is)" >> "$LOG"
    # shellcheck disable=SC2086
    bash "$QUEUE_DIR/run_job.sh" $line >> "$LOG" 2>&1
    echo "[worker$TAG] <<< rc=$? $(date -Is)" >> "$LOG"
  done < "$QUEUE"

  echo "[worker$TAG] queue drained $(date -Is)" >> "$LOG"

  if [[ "$ROLE" == "nophase2" ]]; then
    break
  fi

  NEXT="$QUEUE_DIR/queue_gpu${GPU}_phase2.txt"
  if [[ "$QUEUE" == "$NEXT" ]]; then
    break   # phase 2 itself has now drained
  fi

  # Phase 2 needs the winner, so it can only be generated once BOTH workers
  # have finished phase 1. Poll until phase2.py reports phase 1 complete.
  waited=0
  while [[ ! -f "$NEXT" ]]; do
    "$PY" "$QUEUE_DIR/phase2.py" >> "$LOG" 2>&1 && break
    sleep 120
    waited=$(( waited + 120 ))
    if [[ $waited -ge 10800 ]]; then
      echo "[worker$TAG] phase2 wait timed out after ${waited}s" >> "$LOG"
      break
    fi
  done

  if [[ -f "$NEXT" ]]; then
    QUEUE="$NEXT"
    continue
  fi
  break
done

echo "[worker$TAG] ALL DONE $(date -Is)" >> "$LOG"
